### ISSUE TITLE
ダミー実装

### ISSUE THREAD

**Issue by dondakeshimo** [dondakeshimo/system-trading#4]
## 概要
ダミー実装を行う。
複数回に分けてPRを出す。
ダミー実装と言っても一旦は動くところまでを作成する。
データや計算結果、モデルがダミーという話。

## 目的
実装の土台ができる

## 完了条件
コントリビュータが設計に大きく迷わず開発できるような状態

## 結論
クローズする際に最終的にどうなったか記載
必要があればリンクなども付与

**Comment by dondakeshimo** [comment]
## TODO

- [ ] feature_intructor
- [ ] usecases/find_stock_to_buy
- [ ] usecases/notify_stock_to_buy
- [ ] cli, controllers
- [ ] logger, progress information

**Comment by dondakeshimo** [comment]
#5 #7 #8 #12 #15 #17 を持って完了
